export const ADD_SOUND = 'ADD_SOUND';
export const REMOVE_SOUND = 'REMOVE_SOUND';
export const SET_AUDIO = 'SET_AUDIO';
export const TOGGLE_AUDIO_PHASE = 'TOGGLE_AUDIO_PHASE';
export const TOGGLE_AUDIO_TICK = 'TOGGLE_AUDIO_TICK';
