// SEND
export const LOAD_CHARTS = 'LOAD_CHARTS';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const SEND_CHECKING_FOR_UPDATES = 'SEND_CHECKING_FOR_UPDATES';
export const SEND_ERROR = 'SEND_ERROR';
export const SEND_GENERAL_ALERT = 'SEND_GENERAL_ALERT';
export const SEND_GIVE_FEEDBACK = 'SEND_GIVE_FEEDBACK';
export const SEND_NEEDS_UPDATE = 'SEND_NEEDS_UPDATE';
export const SEND_NEW_SESSION = 'SEND_NEW_SESSION';
export const SEND_RESET_ROUND = 'SEND_RESET_ROUND';
export const SEND_REPORT_ISSUE = 'SEND_REPORT_ISSUE';

// ON
export const ON_ACCEPT_UPDATE = 'ON_ACCEPT_UPDATE';
