export const SET_APP_SETTINGS = 'SET_APP_SETTINGS';
export const SET_AUDIO = 'SET_AUDIO';
export const SET_AUDIO_OFF = 'SET_AUDIO_OFF';
export const SET_AUDIO_ON = 'SET_AUDIO_ON';
export const SET_ELECTRON_SETTINGS = 'SET_ELECTRON_SETTINGS';
export const SET_THEME = 'SET_THEME';
export const TOGGLE_COMPACT_MODE = 'TOGGLE_COMPACT_MODE';
export const TOGGLE_WELCOME_SLIDES = 'TOGGLE_WELCOME_SLIDES';
