export const SET_APP_SETTINGS = 'SET_APP_SETTINGS';
export const SET_AUDIO_OFF = 'SET_AUDIO_OFF';
export const SET_AUDIO_ON = 'SET_AUDIO_ON';
export const SET_ELECTRON_SETTINGS = 'SET_ELECTRON_SETTINGS';
