// SEND
export const LOAD_CHARTS = 'LOAD_CHARTS';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const SEND_CHECKING_FOR_UPDATES = 'SEND_CHECKING_FOR_UPDATES';
export const SEND_ERROR = 'SEND_ERROR';
export const SEND_GENERAL_ALERT = 'SEND_GENERAL_ALERT';
export const SEND_GIVE_FEEDBACK = 'SEND_GIVE_FEEDBACK';
export const SEND_NEEDS_UPDATE = 'SEND_NEEDS_UPDATE';
export const SEND_NEW_SESSION = 'SEND_NEW_SESSION';
export const SEND_RESET_ROUND = 'SEND_RESET_ROUND';
export const SEND_TOGGLE_COMPACT = 'SEND_TOGGLE_COMPACT';
export const SEND_TOGGLE_WELCOME = 'SEND_TOGGLE_WELCOME';

// ON
export const ON_ACCEPT_UPDATE = 'ON_ACCEPT_UPDATE';
export const ON_CHANGE_COMPACT_MODE = 'ON_CHANGE_COMPACT_MODE';

// EVENTS
export const CHECK_FOR_UPDATES = 'CHECK_FOR_UPDATES';
