// SEND
export const LOAD_CHARTS = 'LOAD_CHARTS';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const SEND_CHECKING_FOR_UPDATES = 'SEND_CHECKING_FOR_UPDATES';
export const SEND_ERROR = 'SEND_ERROR';
export const SEND_GENERAL_ALERT = 'SEND_GENERAL_ALERT';
export const SEND_NEEDS_UPDATE = 'SEND_NEEDS_UPDATE';
export const SEND_NEW_SESSION = 'SEND_NEW_SESSION';
export const SEND_TOGGLE_COMPACT = 'SEND_TOGGLE_COMPACT';

// ON
export const ON_ACCEPT_UPDATE = 'ON_ACCEPT_UPDATE';
export const ON_CHANGE_COMPACT_MODE = 'ON_CHANGE_COMPACT_MODE';

// EVENTS
export const CHECK_FOR_UPDATES = 'CHECK_FOR_UPDATES';
export const DESTROY_TRAY_ICON = 'DESTROY_TRAY_ICON';
export const OPEN_WELCOME_WINDOW = 'OPEN_WELCOME_WINDOW';
export const UPDATE_TRAY_ICON = 'UPDATE_TRAY_ICON';
export const UPDATE_TRAY_TIMER = 'UPDATE_TRAY_TIMER';

// IPC MAIN
export const CREATE_WELCOME_WINDOW_ON_MAIN = 'CREATE_WELCOME_WINDOW_ON_MAIN';
